### PR TITLE
cleaning up styles and views

### PR DESCRIPTION
**Pull request by KrzysiekKuczma**

### CODE REVIEW

**Review by LachPawel — APPROVED** [review]

**Review by Confidenceiskey — CHANGES_REQUESTED** [review]
Some fixes are needed. Doing this to prevent accidental merge

**Comment by Confidenceiskey** [comment]
See bottom (white section seeping through).

1. What happened to the setting's gear icon? It is now a button?

Screenshot 2024-01-04 at 11 48 00 AM

**Comment by Confidenceiskey** [comment]
More comments (this is testing on **web**)

1. I tried doing the exercise analysis and it froze at the 0 second mark (maybe not related to this PR)
2. I created a new user, did the body analysis and the data isn't being saved (it isn't letting me generate a meal or diet plan).
3. UI clash on the body analysis screen with the body/description and the target weight/body fat %

Screenshot 2024-01-04 at 11 58 15 AM
Screenshot 2024-01-04 at 11 57 23 AM


Screenshot 2024-01-04 at 11 56 50 AM
Screenshot 2024-01-04 at 11 56 26 AM
Screenshot 2024-01-04 at 11 55 58 AM

**Comment by Confidenceiskey** [comment]
Should also fix this to not show this N/A stuff
Screenshot 2024-01-04 at 12 08 38 PM

**Comment by KrzysiekKuczma** [comment]
I moved settings to a button, this way it's more coherent with the rest os application.

Excercise Analysis will be refactored today.
All clash issues wil be addressed today. I also did test it on web and it worked properly. I will retest it now

**Pull request merged**
